name: Deplot Multik8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t vmun1x/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true vmun1x/react-test npm test

      - name: Set Service key
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{secrets.GKE_SA_KEY}}"

      - name: Set Project
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          project_id: multi-k8s-455903

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: "google-github-actions/get-gke-credentials@v0"
        with:
          cluster_name: multi-cluster
          location: asia-northeast3

      - name: Build
        run: |-
          docker build -t vmun1x/multi-client:latest -t vmun1x/multi-client:${{env.SHA}} -f ./client/Dockerfile ./client
          docker build -t vmun1x/multi-server:latest -t vmun1x/multi-server:${{env.SHA}} -f ./server/Dockerfile ./server
          docker build -t vmun1x/multi-worker:latest -t vmun1x/multi-worker:${{env.SHA}} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push vmun1x/multi-client:latest 
          docker push vmun1x/multi-server:latest 
          docker push vmun1x/multi-worker:latest 

          docker push vmun1x/multi-client:${{env.SHA}} 
          docker push vmun1x/multi-server:${{env.SHA}}
          docker push vmun1x/multi-worker:${{env.SHA}}

      - name: Apply
        run: |-
          kubectl apply -f k8s

          kubectl set image deployments/client-deployment client=vmun1x/multi-client:${{env.SHA}} 
          kubectl set image deployments/server-deployment server=vmun1x/multi-server:${{env.SHA}} 
          kubectl set image deployments/worker-deployment worker=vmun1x/multi-worker:${{env.SHA}}
